### ISSUE TITLE
Adjust .travis.yml to enable caching

### ISSUE THREAD

**Issue by jtyost2** [loadsys/CakePHP-Plugin-Skeleton#13]
Add this line to the top of the file:
```yml
sudo: false
```

Add these lines:
```yml
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
```

After the matrix but before installation
